# urd shell integration for bash. Generated by `urd hook bash`; do not edit by hand.
# A second load is cut off by if, not return: a return at the top level would
# leave .bashrc itself and cut off the rest of the config.
if [[ -z ${_urd_loaded-} ]]; then
_urd_loaded=1

_urd_bin=@@BIN@@

# readline offers neither per-character interception nor highlighting inside the
# line, so bash gets a dialog in an external process rather than a live mode.
_urd_pick() {
  local picked
  picked=$("$_urd_bin" pick 2>/dev/tty)
  if [[ -n $picked ]]; then
    READLINE_LINE=$picked
    READLINE_POINT=${#READLINE_LINE}
  fi
}

bind -x '"@@HOTKEY@@": _urd_pick'

fi
