# urd shell integration. Generated by `urd hook zsh`; do not edit by hand.
typeset -g URD_BIN=@@BIN@@
typeset -g URD_TRIGGER=@@TRIGGER@@
typeset -g URD_SOCK=@@SOCK@@
typeset -g URD_INDICATOR=@@INDICATOR@@
typeset -g URD_MODE=@@MODE@@
# zselect timeout in hundredths: under ffmpeg load (500-630% CPU) the daemon's
# p99 rises to 19-26 ms, and 30 ms left no room. 6 = 60 ms.
typeset -g URD_TIMEOUT=6
typeset -g URD_COLOR_PROMPT=@@COLOR_PROMPT@@
typeset -g URD_COLOR_MARK=@@COLOR_MARK@@
typeset -g URD_COLOR_BUILTIN=@@COLOR_BUILTIN@@
typeset -g URD_COLOR_HINT=@@COLOR_HINT@@
typeset -g URD_COLOR_QUERY=@@COLOR_QUERY@@
typeset -g URD_CFG=@@CFG@@
typeset -g URD_CFG_STAMP=@@CFG_STAMP@@
# The root key is the empty string, and ${_urd_tree[""]} in zsh misses it - only a variable reaches it.
typeset -gA _urd_tree=(@@TREE@@)
typeset -gA _urd_defaults=(@@DEFAULTS@@)
typeset -gA _urd_hints=(@@HINTS@@)
# Both tables: an associative array in zsh has no order, and a hint has to keep the order Commands declares.
typeset -gA _urd_alias=(@@ALIAS@@)
typeset -gA _urd_short=(@@SHORT@@)

_urd_spawn() {
  (( _urd_spawned )) && return
  _urd_spawned=1
  ("$URD_BIN" serve >/dev/null 2>&1 &)
}

_urd_drop() {
  if (( _urd_fd > 0 )); then
    exec {_urd_fd}>&- 2>/dev/null
  fi
  _urd_fd=0
}

_urd_connect() {
  (( _urd_fd > 0 )) && return 0
  [[ -S $URD_SOCK ]] || { _urd_spawn; return 1 }
  zsocket $URD_SOCK 2>/dev/null || { _urd_spawn; return 1 }
  _urd_fd=$REPLY
  return 0
}

_urd_ask_socket() {
  [[ $URD_MODE == daemon ]] || return 1
  (( _urd_socket_dead )) && return 1
  _urd_connect || return 1
  print -u $_urd_fd -r -- "Q $_urd_nav $_urd_query" 2>/dev/null || { _urd_drop; return 1 }
  zselect -t $URD_TIMEOUT -r $_urd_fd >/dev/null 2>&1 || { _urd_socket_dead=1; _urd_drop; return 1 }
  local head
  IFS= read -r -u $_urd_fd head 2>/dev/null || { _urd_drop; return 1 }
  if [[ $head != urd1\ * ]]; then
    _urd_drop
    _urd_protocol_bad=1
    return 1
  fi
  IFS= read -r -u $_urd_fd _urd_cmd 2>/dev/null || { _urd_drop; return 1 }
  IFS= read -r -u $_urd_fd _urd_spans 2>/dev/null || { _urd_drop; return 1 }
  _urd_total=${${(z)head}[2]}
  _urd_idx=${${(z)head}[3]}
  return 0
}

_urd_ask_oneshot() {
  local -a out
  # Split on the space, not through (z): (z) would eat the quote in a query like don't.
  out=("${(@f)$("$URD_BIN" query $_urd_nav ${(s: :)_urd_query} 2>/dev/null)}")
  [[ ${out[1]} == urd1\ * ]] || return 1
  _urd_total=${${(z)out[1]}[2]}
  _urd_idx=${${(z)out[1]}[3]}
  _urd_cmd=${out[2]}
  _urd_spans=${out[3]}
  return 0
}

_urd_ask() {
  _urd_cmd=""
  _urd_spans=""
  _urd_total=0
  _urd_idx=0
  if _urd_ask_socket; then
    _urd_degraded=0
  elif _urd_ask_oneshot; then
    _urd_degraded=1
  else
    _urd_degraded=2
    return 1
  fi
  # The engine clamps nav to the result set; without carrying it back the counter runs past total.
  (( _urd_total > 0 )) && _urd_nav=$_urd_idx
  return 0
}

_urd_is_literal() {
  local -a words
  words=(${(s: :)_urd_query})
  (( ${#words} )) || return 1
  [[ ${words[1]} == -* ]]
}

# Into a variable, not print: capturing output needs $(...), a fork per keystroke.
_urd_suggest_for() {
  local stamp
  local -a found
  case $1 in
    newdump)
      # Tested, not tried: without the module strftime is no builtin and zsh searches PATH per keystroke.
      zmodload -e zsh/datetime || return
      strftime -s stamp '%Y%m%d-%H%M' $EPOCHSECONDS
      _urd_suggest="~/urd_history_$stamp"
      ;;
    newestdump)
      # om - sort by mtime, [1] - newest, N - an empty list instead of an error.
      found=(~/urd_history_*(.om[1]N))
      (( ${#found} )) && _urd_suggest="~/${found[1]:t}"
      ;;
  esac
}

_urd_set_candidates() {
  local node=$1 tail=$2 k a
  local -a kids
  kids=(${(s: :)${_urd_tree[$node]-}})
  _urd_candidates=()
  for k in $kids; do
    if [[ ${k[1,${#tail}]} == "$tail" ]]; then
      _urd_candidates+=$k
      continue
    fi
    for a in ${(s: :)${_urd_short[$k]-}}; do
      if [[ ${a[1,${#tail}]} == "$tail" ]]; then
        _urd_candidates+=$k
        break
      fi
    done
  done
}

_urd_command_view() {
  local -a words kids
  words=(${(s: :)_urd_query})
  _urd_hint=""
  _urd_suggest=""
  _urd_matched_len=0
  _urd_aliased=0

  # Called node, not path: $path in zsh is an array tied to $PATH, and += appended an element.
  local node="" word k
  local -i i matched=0
  for (( i = 1; i <= ${#words}; i++ )); do
    word=${_urd_alias[${words[i]}]:-${words[i]}}
    kids=(${(s: :)${_urd_tree[$node]-}})
    (( ${kids[(Ie)$word]} )) || break
    [[ $word == "${words[i]}" ]] && _urd_aliased=0 || _urd_aliased=1
    [[ -n $node ]] && node+=" "
    node+=$word
    matched=$i
  done
  _urd_node=$node
  _urd_matched=$matched

  # Measured on the query, not by adding word lengths: repeated spaces would shift the highlight.
  local rest=$_urd_query
  for word in ${words[1,matched]}; do
    while [[ ${rest[1]} == ' ' ]]; do
      rest=${rest[2,-1]}
      (( _urd_matched_len++ ))
    done
    rest=${rest[${#word}+1,-1]}
    (( _urd_matched_len += ${#word} ))
  done

  kids=(${(s: :)${_urd_tree[$node]-}})
  if (( matched == ${#words} )); then
    if [[ -n ${_urd_hints[$node]-} ]]; then
      _urd_hint=" [${_urd_hints[$node]}]"
    elif (( ${#kids} )); then
      _urd_hint=" [${(j:|:)kids}]"
    fi
    if [[ $_urd_query == *' ' && -n ${_urd_defaults[$node]-} ]]; then
      _urd_suggest_for ${_urd_defaults[$node]}
    fi
  elif (( matched == ${#words} - 1 )); then
    # A cut prefix, never the pattern "$word*": an asterisk stays a literal whatever globsubst says.
    _urd_set_candidates "$node" "${words[matched+1]}"
    (( ${#_urd_candidates} )) && _urd_hint=" [${(j:|:)_urd_candidates}]"
  fi
}

_urd_set_counter() {
  if (( _urd_degraded == 2 )); then
    _urd_counter="engine unavailable"
  elif (( _urd_total == 0 )); then
    _urd_counter="no match"
  else
    _urd_counter="$((_urd_nav + 1))/$_urd_total"
  fi
}

# The result itself is deliberately not painted: only the matched pieces draw the eye.
_urd_mark_result() {
  local -i at=$1
  local pair a b
  [[ -n $URD_COLOR_MARK ]] || return
  for pair in ${(s: :)_urd_spans}; do
    a=${pair%%:*}
    b=${pair##*:}
    [[ -n $a && -n $b ]] && region_highlight+=("P $((a + at)) $((b + at)) $URD_COLOR_MARK")
  done
}

_urd_render() {
  region_highlight=()
  # Offsets inside PREDISPLAY need the P flag; BUFFER offsets count from its own start.
  local pre="$URD_TRIGGER " info=""
  if (( _urd_literal )); then
    # Trailing spaces are cut: otherwise they double with the space before the hint.
    local head=$_urd_query
    while [[ $head == *' ' ]]; do head=${head[1,-2]}; done
    BUFFER=$head
    if [[ -n $_urd_suggest ]]; then
      # In the buffer rather than the hint, or Enter would not run it.
      BUFFER="$head $_urd_suggest"
    fi
    info=$_urd_hint
    (( _urd_matched_len )) && [[ -n $URD_COLOR_BUILTIN ]] && region_highlight+=("0 $_urd_matched_len $URD_COLOR_BUILTIN")
  elif [[ -z $_urd_query ]]; then
    BUFFER=""
  elif [[ $URD_INDICATOR == suffix ]]; then
    # The cursor lives only inside BUFFER, which is why the query goes there and the result into
    # PREDISPLAY: region_highlight in zsh 5.9 has no blink, and nothing else can make it blink.
    local -i at=0
    if [[ -n $_urd_shown_cmd ]]; then
      at=${#pre}
      pre+="$_urd_shown_cmd "
    fi
    pre+="["
    BUFFER=$_urd_query
    _urd_set_counter
    info=" - $_urd_counter]"
    _urd_mark_result $at
    [[ -n $URD_COLOR_HINT ]] && region_highlight+=("P $(( ${#pre} - 1 )) ${#pre} $URD_COLOR_HINT")
    [[ -n $URD_COLOR_QUERY ]] && region_highlight+=("0 ${#BUFFER} $URD_COLOR_QUERY")
  else
    if [[ -n $_urd_shown_cmd ]]; then
      BUFFER=$_urd_shown_cmd
      _urd_mark_result 0
    fi
    _urd_set_counter
    info=" [$_urd_query - $_urd_counter]"
  fi

  PREDISPLAY=$pre
  CURSOR=${#BUFFER}
  [[ -n $URD_COLOR_PROMPT ]] && region_highlight+=("P 0 ${#URD_TRIGGER} $URD_COLOR_PROMPT")

  case $URD_INDICATOR in
    suffix)
      POSTDISPLAY=$info
      [[ -n $info && -n $URD_COLOR_HINT ]] && region_highlight+=("${#BUFFER} $(( ${#BUFFER} + ${#info} )) $URD_COLOR_HINT")
      ;;
    below)
      POSTDISPLAY=""
      # zle -M redraws the whole area: repeating the same text flickers visibly.
      [[ $info != $_urd_shown ]] && zle -M "$info"
      ;;
    *)
      POSTDISPLAY=""
      ;;
  esac
  _urd_shown=$info
  zle -R
}

_urd_refresh() {
  if _urd_is_literal; then
    _urd_literal=1
    _urd_command_view
    _urd_cmd=""
    _urd_spans=""
    _urd_total=0
    _urd_degraded=0
  else
    _urd_literal=0
    _urd_hint=""
    _urd_suggest=""
    _urd_matched_len=0
    if [[ -n $_urd_query ]]; then
      _urd_ask
      if (( _urd_protocol_bad )); then
        zle -M "urd: protocol mismatch, restart your shell"
        _urd_cancel
        return
      fi
      # Kept apart from the engine's answer: on an empty result the previous candidate must stay on screen.
      (( _urd_total > 0 )) && [[ -n $_urd_cmd ]] && _urd_shown_cmd=$_urd_cmd
    else
      _urd_cmd=""
      _urd_spans=""
      _urd_shown_cmd=""
      _urd_total=0
      _urd_degraded=0
    fi
  fi
  _urd_render
}

_urd_save_state() {
  _urd_saved_buffer=$BUFFER
  _urd_saved_cursor=$CURSOR
  _urd_saved_post=$POSTDISPLAY
  _urd_saved_pre=$PREDISPLAY
  _urd_saved_hl=("${region_highlight[@]}")
}

_urd_restore_decorations() {
  region_highlight=("${_urd_saved_hl[@]}")
  POSTDISPLAY=$_urd_saved_post
  PREDISPLAY=$_urd_saved_pre
}

# Reprints the glue when the config changed, which is what applies an edit without a new shell.
# mtime has no sub-second part: an edit in the same second as the shell start, size unchanged, is missed.
_urd_reload_if_changed() {
  zmodload -e zsh/stat || return
  # -H, not two +element arguments: zstat takes at most one and reports the second as a missing file.
  local -A st
  zstat -H st -- "$URD_CFG" 2>/dev/null || return
  local stamp="$st[mtime] $st[size]"
  [[ $stamp == $URD_CFG_STAMP ]] && return
  # Captured first: on a config it refuses, hook prints nothing, and eval of nothing would leave no functions.
  local fresh
  fresh=$("$URD_BIN" hook zsh 2>/dev/null) || return
  [[ -n $fresh ]] || return
  eval "$fresh"
}

# $1 - the initial query, $2 - the line that cancelling returns to.
_urd_start() {
  _urd_reload_if_changed
  _urd_save_state
  _urd_saved_buffer=$2
  _urd_saved_cursor=${#2}
  _urd_query=$1
  _urd_nav=0
  _urd_spawned=0
  _urd_socket_dead=0
  _urd_protocol_bad=0
  _urd_partial=""
  _urd_shown=""
  _urd_shown_cmd=""
  BUFFER=""
  CURSOR=0
  zle -K urd
  _urd_refresh
}

_urd_leave() {
  zle -K main
  zle -R
}

_urd_cancel() {
  _urd_restore_decorations
  BUFFER=$_urd_saved_buffer
  CURSOR=$_urd_saved_cursor
  _urd_leave
}

_urd_accept() {
  _urd_restore_decorations
  if (( _urd_literal )); then
    # The buffer, not the query: without the prefix the line would read "--cfg" with nothing to run.
    BUFFER="$URD_TRIGGER $BUFFER"
    CURSOR=${#BUFFER}
    _urd_leave
    zle .accept-line
    return
  elif (( _urd_total > 0 )) && [[ -n $_urd_cmd ]]; then
    BUFFER=$_urd_cmd
  else
    BUFFER=$_urd_saved_buffer
  fi
  CURSOR=${#BUFFER}
  _urd_leave
}

_urd_back() {
  _urd_query=${_urd_query[1,-2]}
  if [[ -z $_urd_query ]]; then
    _urd_restore_decorations
    # No space: a space opened the mode, so backspace has to close it the same way.
    BUFFER="$URD_TRIGGER"
    CURSOR=${#BUFFER}
    _urd_leave
    return
  fi
  _urd_nav=0
  _urd_refresh
}

_urd_set_prefix() {
  local -a list=("$@")
  local first=${list[1]} other
  local -i n=${#first} i
  for other in ${list[2,-1]}; do
    (( ${#other} < n )) && n=${#other}
    for (( i = 1; i <= n; i++ )); do
      if [[ ${first[i]} != "${other[i]}" ]]; then
        (( n = i - 1 ))
        break
      fi
    done
  done
  _urd_completion=${first[1,n]}
}

_urd_complete() {
  (( _urd_literal )) || return
  local -a words
  words=(${(s: :)_urd_query})
  local tail=""
  if [[ $_urd_query != *' ' ]] && { (( ${#words} > _urd_matched )) || (( _urd_aliased )) }; then
    tail=${words[-1]}
  fi
  local cnode=$_urd_node
  (( _urd_aliased )) && cnode=""
  _urd_set_candidates "$cnode" "$tail"
  local -a cand
  cand=($_urd_candidates)
  (( ${#cand} )) || return
  if (( ${#cand} == 1 )); then
    _urd_completion=${cand[1]}
  else
    _urd_set_prefix $cand
  fi
  [[ $_urd_completion != "$tail" ]] || return
  _urd_query=${_urd_query[1,-$(( ${#tail} + 1 ))]}$_urd_completion
  (( ${#cand} == 1 )) && _urd_query+=" "
  _urd_nav=0
  _urd_refresh
}

_urd_older() { (( _urd_nav++ )); _urd_refresh }
_urd_newer() { (( _urd_nav > 0 )) && (( _urd_nav-- )); _urd_refresh }
_urd_clear() { _urd_query=""; _urd_nav=0; _urd_refresh }

_urd_passthrough() {
  local k=$KEYS
  _urd_cancel
  zle -U -- "$k"
}

_urd_key() {
  case $KEYS in
    [[:print:]]*)
      _urd_query+=$KEYS
      _urd_nav=0
      _urd_refresh
      ;;
    *)
      _urd_passthrough
      ;;
  esac
}

# A byte above 0x7f arrives as its own keystroke even under MULTIBYTE: measured,
# the widget is called twice for "p" with one byte in $KEYS. Glued back here.
_urd_wide_key() {
  _urd_partial+=$KEYS
  if [[ $_urd_partial == [[:print:]] ]]; then
    _urd_query+=$_urd_partial
    _urd_partial=""
    _urd_nav=0
    _urd_refresh
    return
  fi
  # A UTF-8 character is never longer than four bytes: so this is garbage.
  (( ${#_urd_partial} >= 4 )) && _urd_partial=""
}

_urd_maybe_start() {
  # Quoted: unquoted the value reads as a pattern, and a trigger with an asterisk would not match.
  if [[ $BUFFER == "$URD_TRIGGER" ]] && (( CURSOR == ${#BUFFER} )); then
    _urd_start "" ""
    return
  fi
  zle .self-insert
}

_urd_hotkey() { _urd_start "$BUFFER" "$BUFFER" }

# Before any bindkey: bindkey to a name zle does not know yet fails.
zle -N _urd_key
zle -N _urd_wide_key
zle -N _urd_back
zle -N _urd_accept
zle -N _urd_cancel
zle -N _urd_older
zle -N _urd_newer
zle -N _urd_clear
zle -N _urd_passthrough
zle -N _urd_complete
zle -N _urd_maybe_start
zle -N _urd_hotkey

# Cut off by if, not return: a return at the top level of eval would end .zshrc itself.
if [[ -z ${_urd_loaded-} ]]; then
typeset -g _urd_loaded=1

zmodload zsh/net/socket 2>/dev/null
zmodload zsh/zselect 2>/dev/null
zmodload zsh/stat 2>/dev/null
zmodload zsh/datetime 2>/dev/null

# Guarded although idempotent: zeroing _urd_fd without exec {fd}>&- would leak the open descriptor.
typeset -g _urd_fd=0 _urd_query="" _urd_nav=0 _urd_idx=0 _urd_spawned=0 _urd_socket_dead=0 _urd_protocol_bad=0
typeset -g _urd_cmd="" _urd_spans="" _urd_total=0 _urd_degraded=0 _urd_literal=0
typeset -g _urd_saved_buffer="" _urd_saved_cursor=0 _urd_saved_post="" _urd_saved_pre=""
typeset -g _urd_shown="" _urd_partial="" _urd_shown_cmd="" _urd_counter=""
typeset -g _urd_hint="" _urd_suggest="" _urd_matched_len=0
typeset -g _urd_node="" _urd_matched=0 _urd_completion="" _urd_aliased=0
typeset -ga _urd_candidates
typeset -ga _urd_saved_hl

# bindkey -N recreates the keymap empty: a repeat would wipe what the human bound in it.
bindkey -N urd
# The ranges too: re-applying them would take back a key bound by hand inside one.
bindkey -M urd -R $'\x00'-$'\x1f' _urd_passthrough
bindkey -M urd -R $'\x20'-$'\x7e' _urd_key
bindkey -M urd -R $'\x80'-$'\xff' _urd_wide_key

fi

bindkey -M urd '^I' _urd_complete
bindkey -M urd $'\x7f' _urd_back
bindkey -M urd '^H' _urd_back
bindkey -M urd '^M' _urd_accept
bindkey -M urd '^J' _urd_accept
# ^C never reaches zle: the terminal turns it into SIGINT. Kept for terminals with intr disabled.
bindkey -M urd '^C' _urd_cancel
bindkey -M urd '^G' _urd_cancel
bindkey -M urd '^U' _urd_clear
bindkey -M urd '^P' _urd_older
bindkey -M urd '^N' _urd_newer
bindkey -M urd '^[' _urd_cancel
bindkey -M urd '^[[A' _urd_older
bindkey -M urd '^[OA' _urd_older
bindkey -M urd '^[[B' _urd_newer
bindkey -M urd '^[OB' _urd_newer
bindkey -M urd '^[[200~' _urd_passthrough

bindkey ' ' _urd_maybe_start
# A changed hotkey still needs a new tab: the previous binding cannot be revoked unseen.
@@HOTKEY_BINDING@@
